### ISSUE TITLE
Issue with Identity Server 3

### ISSUE THREAD

**Issue by courtenayparserr** [angusmillar/Deprecated-Pyro#4]
Hi Angus,

Me again :-)

Been trying to fire-up the Identity side of things. Im on branch "develop-r4" although have made some adjustments.

I keep getting the following issue with the Authentication server. I am running one, but its a separate web app running on Identity Server 4.

![image](https://user-images.githubusercontent.com/24819057/61677555-6460f280-ad43-11e9-8c6a-9a62af69bc2f.png)

You don't by any chance have a working copy of your auth server? (The one at https://localhost:44300/)

**Comment by angusmillar** [comment]
project deprecated
